### ISSUE TITLE
Odd issue with enabling non-existent mods

### ISSUE THREAD

**Issue by Ikethepro18** [MohammedGamer85/Mythtic#63] opened 2023-09-28 20:05 UTC
I had previously installed a test mod that no longer has any associated files in the 'DownLoaded' folder. As such when I tried to enable the mod I got the following popup
![](https://i.imgur.com/8hNI6Hy.png)

However I managed to somehow get it into a state where it was disabled on the Home screen, but when I clicked on the mod to view more details, it was enabled. And then returning to the Home screen would popup the same error shown above. Unfortunately the app didn't appear to make a log of this in the expected location so I can't provide one. If logs are no longer written to `\Mythtic\Logs` then please let me know where they are written to

Also may be unrelated but when I then clicked on a mod downloaded from Mythos, the app crashed completely and just before I encountered this issue I had just deleted a mod that also didn't have any files

**Comment by MohammedGamer85** [comment] 2023-09-28 20:16
The reason the app crashed when you tried to load your modes modpage is because the mod images are saved differently now so the app does not know how to load old files + the account.json is also slitly different ss some other changes that is why I am not reusing the old files.

**Comment by MohammedGamer85** [comment] 2023-09-28 20:17
I also redid multiple other things so I recommend you to delete any mod related files you might have copied from from the old version and delete the importedmods.json

**Comment by MohammedGamer85** [comment] 2023-09-28 20:17
I also redid multiple other things so I recommend you to delete any mod related files you might have copied from from the old version and delete the importedmods.json

**Comment by MohammedGamer85** [comment] 2023-09-28 20:17
@Ikethepro18

**Comment by MohammedGamer85** [comment] 2023-09-28 20:20
@Ikethepro18 Logs are created for me completely fine.
![image](https://github.com/MohammedGamer85/Mythtic/assets/100155245/9d45caf8-a4b7-4b01-9eae-afc268846655)

**Comment by Ikethepro18** [comment] 2023-09-28 21:14
1. The mod I opened when the app crashed was one that I had installed with the latest prelease of 1.0
2. No mod files were transferred over to the new app
3. A log was created, it was just hard to see because it had been interlaced with logs from the 27th and 30th of August. I would send the log but I'm not sure which it was

**Comment by MohammedGamer85** [comment] 2023-09-28 21:29
Oder the files by date modified and send a couple of the last onces

**Comment by MohammedGamer85** [comment] 2023-09-29 00:50
> 1. The mod I opened when the app crashed was one that I had installed with the latest prelease of 1.0
> 2. No mod files were transferred over to the new app
> 3. A log was created, it was just hard to see because it had been interlaced with logs from the 27th and 30th of August. I would send the log but I'm not sure which it was
> 

Did you by any chance have that kod enabled in the last app as that might be why it crashed

**Comment by MohammedGamer85** [comment] 2023-09-29 00:51
The objective reference is not set to a instant of a objective means something equals null but the log file is what includes details on what is null @Ikethepro18

**Comment by Ikethepro18** [comment] 2023-09-29 06:56
> Did you by any chance have that kod enabled in the last app as that might be why it crashed

I wouldn't think so. The mod wasn't there when I manually imported old settings etc. The mod in question I had just downloaded from Mythos via the app

I'll send some logs when I can later today

**Comment by MohammedGamer85** [comment] 2023-09-29 13:47
> > Did you by any chance have that kod enabled in the last app as that might be why it crashed
> 
> I wouldn't think so. The mod wasn't there when I manually imported old settings etc. The mod in question I had just downloaded from Mythos via the app
> 
> I'll send some logs when I can later today

I will be waitting for the logs as without them i can't really  pin point what the problem is as i can't recreate it.

**Comment by MohammedGamer85** [comment] 2023-10-31 06:57
Hay listen, I will mark this "won't fix" and closed if you do find out what caused it or any leads just send them in here and I will reopen it.@Ikethepro18

**Closed** 2023-10-31 06:58 UTC
Labels: wontfix, on pause
